'use server';

/**
 * @fileOverview Generates CAPS-compliant educational content.
 *
 * Models (per EduAI Companion architecture — chat.txt):
 *   Text generation:  gemini-3.1-pro          — flagship model for all educational content
 *   Image generation: gemini-3-flash-image     — high-fidelity classroom poster/visual generation
 *
 * Architecture:
 *  1. gemini-3.1-pro generates the content body in Markdown with [IMAGE:VAn] placeholders.
 *  2. A `visualAids` JSON array provides a detailed prompt per image.
 *  3. fetchImage() calls gemini-3-flash-image for each visual aid concurrently.
 *  4. Placeholders are resolved to media URLs / base64 data URIs for the renderer.
 */

import { z } from 'zod';
import { ai } from '../../genkit';
import { googleAI } from '@genkit-ai/google-genai';

const GenerateCAPSContentInputSchema = z.object({
  grade: z.string().describe('The grade level (R, 1-12, or custom).'),
  subject: z.string(),
  topic: z.string(),
  contentType: z.string(),
  category: z.string(),
  term: z.string().optional(),
  language: z.string().optional(),
  learnerProfile: z.string().optional(),
  objective: z.string().optional(),
  duration: z.string().optional(),
  additionalInstructions: z.string().optional(),
  teacherName: z.string().optional(),
});
export type GenerateCAPSContentInput = z.infer<typeof GenerateCAPSContentInputSchema>;

const CapsResponseSchema = z.object({
  content: z.string().describe('The generated educational content in Markdown.'),
  visualAids: z
    .array(
      z.object({
        id: z.string().describe('Placeholder ID matching [IMAGE:VAn] in content, e.g., VA1.'),
        query: z.string().describe(
          'Detailed, child-safe prompt for gemini-3-flash-image. Include: colourful flat illustration style, subject matter, South African context, grade-level audience.'
        ),
      })
    )
    .describe('Visual aids to be generated by gemini-3-flash-image and embedded in the content.'),
});

export type GenerateCAPSContentOutput = {
  content: string;
  visualAids: { id: string; url: string }[];
};

/**
 * Generates a classroom illustration using gemini-3-flash-image.
 * Returns a media URL or base64 data URI, or empty string on failure (graceful degradation).
 */
async function fetchImage(query: string): Promise<string> {
  try {
    const imageResponse = await ai.generate({
      model: googleAI.model('gemini-3-flash-image'),
      prompt: `Act as a graphic designer. Create a high-resolution, vibrant and educational classroom poster or illustration. Safe for South African primary school children. Colourful flat-design style, clear labels and text. Subject: ${query}`,
      output: { format: 'media' },
    });

    // Primary path: Genkit media URL
    if (imageResponse.media?.url) {
      return imageResponse.media.url;
    }

    // Fallback: check response candidates for inlineData (base64)
    const parts = (imageResponse as any).candidates?.[0]?.message?.content;
    if (Array.isArray(parts)) {
      for (const part of parts) {
        if (part?.media?.url) return part.media.url;
        if (part?.inlineData?.data) {
          const { data, mimeType } = part.inlineData;
          return `data:${mimeType ?? 'image/png'};base64,${data}`;
        }
      }
    }

    console.warn('gemini-3-flash-image returned no usable image for query:', query);
    return '';
  } catch (e) {
    console.error('gemini-3-flash-image generation failed for query:', query, e);
    return '';
  }
}

export async function generateCAPSContent(
  input: GenerateCAPSContentInput
): Promise<GenerateCAPSContentOutput> {
  try {
    const response = await ai.generate({
      model: googleAI.model('gemini-3.1-pro'),
      output: { schema: CapsResponseSchema },
      system: `You are an expert South African Senior Curriculum Specialist and CAPS designer for Grades R-12, with 20+ years of classroom and curriculum development experience.

CRITICAL RULE - CAPS COMPLIANCE:
Every piece of content you generate MUST strictly adhere to the South African CAPS (Curriculum and Assessment Policy Statement) curriculum documents for the specific subject, grade, and term. This is a non-negotiable legal and pedagogical requirement.

CONTENT RULES:
- Use South African English spelling at all times: colour, realise, learner, educator, practise, organise, maths, etc.
- Use South African contexts: local names (Sipho, Aisha, Pieter, Zanele, Thabo), provinces, SA flora and fauna, Rands (ZAR), local landmarks and cultural references.
- Adapt language and cognitive demand exactly to CAPS requirements for the specified grade:
  * Grades R-3 (Foundation Phase): Simple vocabulary, concrete examples, scaffolded step-by-step instructions, playful encouraging tone.
  * Grades 4-6 (Intermediate Phase): Clear learner-friendly text, basic problem-solving, semi-formal language.
  * Grades 7-9 (Senior Phase): Higher-order questions, critical thinking, formal academic register.
  * Grades 10-12 (FET Phase): High academic rigour, exam-style phrasing aligned with past NSC papers, Bloom's Taxonomy levels 4-6.
- Lesson Plans MUST follow: Hook -> Direct Instruction -> Guided Practice -> Independent Practice -> Exit Ticket.
- IDPs/ILDPs MUST include: SMART goals, Accommodations and Modifications, weekly milestones, strategies matched to the learner's learning style.
- Assessments MUST include a clearly marked Answer Key/Memo and a mark allocation table.

FORMATTING RULES:
- Output the main content body as clean Markdown with proper headers, bold, tables and bullet points.
- For Lesson Plans and IDPs, use Markdown tables for at-a-glance summaries.
- NO generic filler text. Be specific, practical and immediately usable by a South African teacher.

VISUAL AID RULES:
- Where an image or illustration enhances learning, insert a placeholder tag EXACTLY like this: [IMAGE:VA1], [IMAGE:VA2], etc.
- Use 2-4 images per piece of content, placed naturally in context.
- In the visualAids JSON array, provide one detailed gemini-3-flash-image prompt per placeholder. Include: colourful flat-design illustration style, subject matter, South African context where relevant, grade-appropriate audience.`,

      prompt: `Generate a ${input.contentType} for Grade ${input.grade}.
Subject: ${input.subject}
Topic: ${input.topic}
Category: ${input.category}
Term: ${input.term || 'N/A'}
Language of instruction: ${input.language || 'English'}
Objective / Learning Outcome: ${input.objective || 'N/A'}
Learner Profile / Barriers to Learning: ${input.learnerProfile || 'General class'}
Length / Duration: ${input.duration || 'Default (30-min lesson / 10-question assessment)'}
Additional Instructions: ${input.additionalInstructions || 'None'}
Teacher Name: ${input.teacherName || 'Educator'}`,
    });

    if (!response.output) {
      throw new Error('Content generation returned no structured output.');
    }
    const { content, visualAids } = response.output;

    // Generate all visual aids concurrently for optimal performance
    const imagePromises = visualAids.map(async (aid) => ({
      id: aid.id,
      url: await fetchImage(aid.query),
    }));

    const resolvedVisualAids = await Promise.all(imagePromises);

    return { content, visualAids: resolvedVisualAids };
  } catch (error) {
    console.error('generateCAPSContent error:', error);
    throw new Error(
      `Content generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}
